### ISSUE TITLE
Support installation through homebrew on mac

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-incubator/apiserver-builder-alpha#129]

**Comment by metmajer** [comment]
@pwittrock: I've recently come across this fantastic project. If contributions are welcome, feel free to assign it to me and I'll look into it!

**Comment by pwittrock** [comment]
Consider is assigned.  Just invited you as a collaborator, which allow me to *actually* assign it to you.

**Comment by metmajer** [comment]
Cool, thanks for bringing me on board!

**Comment by metmajer** [comment]
@pwittrock, let's have a discussion over the scope of this issue after I've done some research. 

Creating support for installation via homebrew involves creating a _formula_. A formula points to a specific source code archive and defines methods for _installation_ and _testing_. A formula can be part of the official [homebrew-core](https://github.com/Homebrew/homebrew-core) project, which allows convenient installation via, e.g., `brew install kubernetes-apiserver-builder`. However, I am not sure this is a good fit for a project that is still in a very early stage and that has frequent updates.

The alternative is to provide our formula in a _tap_, a third party repo for formulae. Since we own the tap, we can update the formulae at any time (e.g. for version bumps). In this case, an installation via `brew install kubernetes-incubator/apiserver-builder/apiserver-builder@0.1` would point to a formula defined in `github.com/kubernetes-incubator/homebrew-apiserver-builder/**/apiserver-builder@0.1.rb`. This means that, with this approach, we'd need to create an extra repo in the _kubernetes-incubator_ GitHub organization and I am not sure whether this is accepted.

A consolidated approach would store the tap in this repository, by convention under a directory named `HomebrewFormula` or `Formula`. Here, the installation would look as follows:

```
// clones our repo into a local tap store named ´kubernetes-incubator/apiserver-builder´
brew tap kubernetes-incubator/apiserver-builder https://github.com/kubernetes-incubator/apiserver-builder.git
// now, users can install our formulae as if they were part of Homebrew's canonical repo
brew install kubernetes-apiserver-builder@0.1
// users can also apply updates via
brew update
```

Thoughts?

**Comment by pwittrock** [comment]
@metmajer 

I like the third approach.

The project is just in its infancy, so minimizing overhead and optimizing for making it easy to push lots of releases makes sense to me.  It is probably not worth creating another repo for the formula with the project at this stage.

**Comment by metmajer** [comment]
While debugging the homebrew formula, I came across the following issue:

```
bash-3.2$ make build
rm -rf *.deb *.rpm *.tar.gz ./release
go run ./cmd/apiserver-builder-release/main.go vendor --version 0.1-alpha.15
cmd/apiserver-builder-release/main.go:30:2: cannot find package "github.com/spf13/cobra" in any of:
	/usr/local/Cellar/go/1.9/libexec/src/github.com/spf13/cobra (from $GOROOT)
	/private/tmp/apiserver-builder-20170924-4536-bsljtb/apiserver-builder-0.1-alpha.17/src/github.com/spf13/cobra (from $GOPATH)
make: *** [build] Error 1
```

I am wondering why go does not find the dependency package in the `vendor` folder where it resides? After all, isn't that the point of this directory? I am still quite new to go, but anyone in this round able to help out with an explanation? Thanks!

**Comment by pwittrock** [comment]
@metmajer 

I think your directory structure may be off.  Go expects the go to be under `$GOPATH/src/<go-package-name>`, so the package `github.com/kubernetes-incubator/apiserver-boot` should live under `$GOPATH/src/github.com/kubernetes-incubator/apiserver-boot`.

If your GOPATH is `/private/tmp/apiserver-builder-20170924-4536-bsljtb/apiserver-builder-0.1-alpha.17` then the apiserver-builder repo should be checkout out in `/private/tmp/apiserver-builder-20170924-4536-bsljtb/apiserver-builder-0.1-alpha.17/src/github.com/kubernetes-incubator/apiserver-builder` and you should run make from there.

I am not sure why it cannot find the vendor, but it maybe that it is looking for the vendor directory under `/private/tmp/apiserver-builder-20170924-4536-bsljtb/apiserver-builder-0.1-alpha.17/src/github.com/kubernetes-incubator/apiserver-builder/vendor` and doesn't find it.

**Comment by metmajer** [comment]
Thanks for your feedback @pwittrock, I'll look into your suggestions!

**Comment by pwittrock** [comment]
@metmajer FYI, I have been starting to do some work to integrate Bazel support for faster builds.  I also changed how the glide.tar.gz is done locally instead of through glide.  I've tested the changes quite a bit, but there is still a chance I broke something.

**Comment by pwittrock** [comment]
FYI, i introduced building with bazel which is much faster once you have bazel installed.

```sh
go run cmd/apiserver-builder-release/main.go vendor --version 0.1-alpha.19  && \
go run cmd/apiserver-builder-release/main.go build --version 0.1-alpha.18 --bazel
```

**Comment by metmajer** [comment]
Awesome, I'll make sure this is also reflected in the Makefile. I'm quite a bit busy atm, but will follow up very soon.
