### ISSUE TITLE
Kubernetes java client always uses system:anonymous User even I set credentials

### ISSUE THREAD

**Issue by janakec19** [kubernetes-incubator/apiserver-builder-alpha#378]
Java Sample code:
ApiClient defaultClient = Configuration.getDefaultApiClient();
		String credentials = new String(Base64.getEncoder().encode("username:password".getBytes()));
		ApiKeyAuth basicAuth = (ApiKeyAuth) defaultClient.getAuthentication("BearerToken");
		basicAuth.setApiKey(credentials);
		basicAuth.setApiKeyPrefix("Basic");
		defaultClient.setBasePath("https://192.168.*.*:8000");
		Configuration.setDefaultApiClient(defaultClient);

**Error response:
"**apiVersion":"v1","metadata":{},"status":"Failure","message":"secrets is forbidden: User **\"system:anonymous\"** cannot list resource 

I already created role binding : 
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-manager-binding
  namespace: default
subjects:
- kind: User
  name: kubernetes-admin
  namespace: default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: ""

Why Java client is always using  system:anonymous User even i set username and password?

**Comment by yue9944882** [comment]
i guess this issue should be sent to [the repo for java client](https://github.com/kubernetes-client/java/issues)?

> Why Java client is always using system:anonymous User even i set username and password?

the error is basically suggesting two things:

1. anonymous auth is enabled in your cluster, it's recommended to be off for most cases. otherwise, you'll get a `401/Unauthorized` error
2. the authentication settings of the api-client is not working. please make sure the credentials are valid ones?
